### ISSUE TITLE
request.socket.remoteAddress property doesn't available

### ISSUE THREAD

**Issue by hbakhtiyor** [uNetworking/bindings#20]

**Comment by jrylan** [comment]
Ran into this as well. I'm not running in production yet so I can't accurately test how it would work for real connections, but the remoteAddress is defined in the _socket property during the connection event. 

Try this:

```js
 wss.on('connection', function(socket) {
    console.log(socket._socket)
})
```

You will need to assign the value to another variable or something, because it does get set to null pretty quickly.
